apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-iii.fullname" . }}-pvc
  labels:
    app: {{ template "firefly-iii.name" . }}
    chart: {{ template "firefly-iii.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}