apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-iii.fullname" . }}-config
  labels:
    app: {{ template "firefly-iii.name" . }}
    chart: {{ template "firefly-iii.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.configs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
